name: Build nw.js for ARM64

on:
  push:
    branches: [ nw92 ]
  pull_request:
    branches: [ nw92 ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 gcc-aarch64-linux-gnu g++-aarch64-linux-gnu ninja-build

    - name: Install gn
      run: |
        git clone https://gn.googlesource.com/gn
        cd gn
        python build/gen.py
        ninja -C out
        sudo cp out/gn /usr/local/bin/

    - name: Generate build files
      run: |
        gn gen out/nw --args='is_debug=false is_component_ffmpeg=true target_cpu="arm64"'

    - name: Build nw.js
      run: |
        ninja -C out/nw nwjs

    - name: Build Node
      run: |
        ./build/gyp_chromium -I third_party/node-nw/common.gypi -D building_nw=1 -D clang=1 third_party/node-nw/node.gyp
        ninja -C out/nw node
        ninja -C out/nw copy_node

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: nwjs-arm64
        path: out/nw/nwjs
